"""
Shared Configuration

Configuration needed by BOTH the client and the server. Deliberately
free of secrets and server-only resources: no database URL, no JWT
signing key, no blob-storage root -- those live in config_server.py
and are imported only by server-side modules (D0 -- Configuration &
Network Separation).

The split exists so a client deployment never needs, and can never
accidentally read, credentials that belong to the server. Anything
added here must be safe to ship to every client machine.

Note on the current state (honest scope limit): client code still
reaches the database directly (client/session.py, client/
conversation_store.py, gui/main_window.py), so a client process today
still ends up importing config_server transitively via
database.connection. D0 establishes the boundary; the later phases
that move those database operations behind the server are what make a
client genuinely credential-free.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

ROOT_DIR = Path(__file__).resolve().parent
load_dotenv(ROOT_DIR / ".env")

# ---------------------------------------------------------------
# Network Configuration
#
# Three distinct settings, deliberately not one shared "HOST"
# (D0 -- Configuration & Network Separation). Before this split a
# single hardcoded HOST = "127.0.0.1" served as both the server's bind
# interface and the client's connect target, which made any
# deployment other than "everything on one machine" impossible to
# express.
#
#   SERVER_BIND_HOST -- server only: which local interface to listen
#                       on. Defaults to loopback, so a development
#                       server is NOT reachable from other devices
#                       unless that exposure is opted into explicitly
#                       (set 0.0.0.0 for LAN/internet).
#   SERVER_HOST      -- client only: the address to dial, and the
#                       hostname verified against the server
#                       certificate's SAN during the TLS handshake.
#   SERVER_PORT      -- both: the TCP port, which must match.
#
# Every default preserves the pre-split single-machine behavior
# exactly.
# ---------------------------------------------------------------

SERVER_BIND_HOST = os.environ.get("SERVER_BIND_HOST", "127.0.0.1")

SERVER_HOST = os.environ.get("SERVER_HOST", "127.0.0.1")

SERVER_PORT = int(os.environ.get("SERVER_PORT", "5000"))

# Communication Configuration
BUFFER_SIZE = 1024
ENCODING = "utf-8"

# Key Exchange Configuration
# Choose which algorithm establishes the AES-256 session key.
# "KYBER" -> post-quantum ML-KEM-768 key encapsulation
# "RSA"   -> classical RSA-2048 encryption (kept for benchmarking)
KEY_EXCHANGE_ALGORITHM = "KYBER"

# ---------------------------------------------------------------
# TLS Configuration
#
# Transport-layer security for the client-server TCP connection --
# independent of the Kyber/AES-256-GCM end-to-end encryption already
# applied to message content (crypto/key_manager.py). Overridable via
# environment for a real deployment's certificate/CA; the development
# defaults point at the throwaway development CA and server
# certificate generated by scripts/generate_dev_certs.py under
# certs/dev/ (gitignored -- see docs/architecture/tls_transport.md).
#
# Shared rather than server-only: the server needs the certificate and
# private key, the client needs the CA certificate to verify against.
# None of these paths is itself a secret (the private key's *contents*
# are, and that file never leaves the server).
# ---------------------------------------------------------------

TLS_CERT_FILE = os.environ.get(
    "TLS_CERT_FILE", str(ROOT_DIR / "certs" / "dev" / "server.crt")
)
TLS_KEY_FILE = os.environ.get(
    "TLS_KEY_FILE", str(ROOT_DIR / "certs" / "dev" / "server.key")
)
TLS_CA_FILE = os.environ.get(
    "TLS_CA_FILE", str(ROOT_DIR / "certs" / "dev" / "ca.crt")
)

# Subject Alternative Names baked into the generated development
# server certificate (scripts/generate_dev_certs.py). Python's ssl
# module matches only SAN entries, never the Common Name, and the
# client verifies SERVER_HOST against them -- so every address clients
# use to reach the server must appear here. Configurable (D0) rather
# than hardcoded so a LAN IP or DNS name can be added for multi-device
# deployment without editing the generator; the default reproduces the
# previous hardcoded pair exactly.
TLS_CERT_SANS = tuple(
    entry.strip()
    for entry in os.environ.get("TLS_CERT_SANS", "127.0.0.1,localhost").split(",")
    if entry.strip()
)

# ---------------------------------------------------------------
# Attachment Size Limit (client-side, Phase 8 -- File & Image
# Transfer)
#
# The existing wire framing (utils/network.py) is a single length-
# prefixed JSON packet with no chunking/streaming -- an attachment is
# base64-encoded and held fully in memory on both ends as one packet.
# This cap is enforced client-side, before a file is read or
# encrypted, to keep that whole-message-in-memory model within a
# reasonable bound for this project's scope. Overridable via
# environment for a deployment that wants a different limit.
# ---------------------------------------------------------------

MAX_ATTACHMENT_SIZE_BYTES = int(
    os.environ.get("MAX_ATTACHMENT_SIZE_BYTES", str(25 * 1024 * 1024))
)

# ---------------------------------------------------------------
# Request/Response Timeout (client-side, D1 -- Request/Response
# Infrastructure)
#
# How long a caller using ClientSession.send_request()/
# utils.request_registry.PendingRequestRegistry waits for a
# correlated reply before giving up (see that module for the full
# mechanism). Purely client-side -- the server never blocks waiting
# for a reply, so it has no equivalent setting. Overridable via
# environment for a slow/high-latency deployment.
# ---------------------------------------------------------------

REQUEST_TIMEOUT_SECONDS = float(os.environ.get("REQUEST_TIMEOUT_SECONDS", "10"))

# Application Information
APP_NAME = "Quantum-Resistant Secure Communication System"
VERSION = "1.0.0"


def validate_config():
    """
    Validate the shared configuration above.

    Server-only settings (database, JWT, Argon2, blob storage) are
    validated separately by config_server.validate_server_config(), so
    that importing this module never requires credentials a client
    deployment has no business holding.
    """

    if not SERVER_HOST:
        raise ValueError(
            "SERVER_HOST must be a non-empty address the client can dial. "
            "Example: SERVER_HOST=192.168.1.42"
        )

    if not SERVER_BIND_HOST:
        raise ValueError(
            "SERVER_BIND_HOST must be a non-empty interface for the server "
            "to bind. Use 127.0.0.1 for loopback-only or 0.0.0.0 for all "
            "interfaces."
        )

    if not 1 <= SERVER_PORT <= 65535:
        raise ValueError(
            f"SERVER_PORT must be between 1 and 65535 (got {SERVER_PORT})."
        )

    if not TLS_CERT_SANS:
        raise ValueError(
            "TLS_CERT_SANS must list at least one Subject Alternative Name. "
            "Example: TLS_CERT_SANS=192.168.1.42,127.0.0.1,localhost"
        )

    if REQUEST_TIMEOUT_SECONDS <= 0:
        raise ValueError("REQUEST_TIMEOUT_SECONDS must be a positive number.")


validate_config()
